In [3]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt # for making figures
import random
%matplotlib inline

In [4]:
# Read in all the words
words = open('data/names.txt', 'r').read().splitlines()
print(words[:10])

# Build the vocabulary of characters and mappings to/from integers
chars = sorted(list(set(''.join(words))))
stoi = {s: i + 1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i: s for s, i in stoi.items()}
vocab_size = len(itos)

print(f'Character to index mapping: {itos}')
print(f'Vocabulary size: {vocab_size}')

# Shuffle the words
random.seed(42)
random.shuffle(words)


['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia', 'harper', 'evelyn']
Character to index mapping: {1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}
Vocabulary size: 27


In [5]:
# Encode the words with '.' so the model can learn when a name should end
def encode_words(words):
    encoded = []
    for w in words:
        encoded.extend([stoi[ch] for ch in '.' + w ])
    return encoded

encoded = encode_words(words)

In [6]:
encoded[:20]

[0, 25, 21, 8, 5, 14, 7, 0, 4, 9, 15, 14, 4, 18, 5, 0, 24, 1, 22, 9]

In [7]:
# Parameters for creating training and test sets
n = len(encoded)
n1 = int(0.8 * n)
block_size = 8
batch_size = 1

train_seq = encoded[:n1]
dev_seq = encoded[n1:]

In [8]:
def create_pairs(seq, block_size):
    X, Y = [], []
    for i in range(0, len(seq) - block_size, block_size):
        X.append(seq[i:i+block_size])
        Y.append(seq[i+1:i+block_size+1])
    X = torch.tensor(X, dtype=torch.float32)
    Y = torch.tensor(Y, dtype=torch.float32)
    return X, Y

Xtr, Ytr = create_pairs(train_seq, block_size)
Xdev, Ydev = create_pairs(dev_seq, block_size)

In [9]:
# We are sure that we can pass in previous example's hidden layer
print(Xtr[1])
print(Ytr[1])
print(Xtr[2])
print(Ytr[2])
print(Xtr[3])
print(Ytr[3])
print(f'Training data shapes - X: {Xtr.shape}, Y: {Ytr.shape}')
print(f'Development data shapes - X: {Xdev.shape}, Y: {Ydev.shape}')

tensor([ 4.,  9., 15., 14.,  4., 18.,  5.,  0.])
tensor([ 9., 15., 14.,  4., 18.,  5.,  0., 24.])
tensor([24.,  1., 22.,  9.,  5., 14.,  0., 10.])
tensor([ 1., 22.,  9.,  5., 14.,  0., 10., 15.])
tensor([15., 18.,  9.,  0., 10., 21.,  1., 14.])
tensor([18.,  9.,  0., 10., 21.,  1., 14., 12.])
Training data shapes - X: torch.Size([22814, 8]), Y: torch.Size([22814, 8])
Development data shapes - X: torch.Size([5703, 8]), Y: torch.Size([5703, 8])


In [20]:
lr = 0.0001
batch_size = 1
hidden_size = 30
time_steps = 8
input_size = 27

In [22]:
def softmax(x):
    e_x = torch.exp(x - torch.max(x, dim=1, keepdim=True)[0])
    return e_x / torch.sum(e_x, dim=1, keepdim=True)

In [30]:
# Initalize parameters
Fvh = torch.randn(vocab_size, hidden_size) * 0.01
i1vh = torch.randn(vocab_size, hidden_size) * 0.01
i2vh = torch.randn(vocab_size, hidden_size) * 0.01
Ovh = torch.randn(vocab_size, hidden_size) * 0.01

Fhh = torch.randn(hidden_size, hidden_size) * 0.01
i1hh = torch.randn(hidden_size, hidden_size) * 0.01
i2hh = torch.randn(hidden_size, hidden_size) * 0.01
Ohh = torch.randn(hidden_size, hidden_size) * 0.01

bias1 = torch.zeros(1, hidden_size)
bias2 = torch.zeros(1, hidden_size)
bias3 = torch.zeros(1, hidden_size)
bias4 = torch.zeros(1, hidden_size)

output_matrix = torch.randn(hidden_size, vocab_size) * 0.01
output_bias = torch.zeros(vocab_size)

In [35]:
max_iterations = 0

while max_iterations < 100000:
    
    # (1, 30)
    X = {}
    H = {}
    C = {}
    Ct = {}
    preact1 = {}
    preact2 = {}
    preact3 = {}
    preact4 = {}
    act1 = {}
    act2 = {}
    act3 = {}
    act4 = {}
    logits = {}
    
    # Loop over all batches
    for batch_num in range(Xtr.shape[0]):
        
### --------------------------------------------------------------------------------------------------------------
        
        # Forward propagation 
        
### --------------------------------------------------------------------------------------------------------------
        
        # Get a batch of random numbers into correct shape
        Xb = Xtr[batch_num, :] # (1, 8)
        Xb = Xb.to(torch.long) # (1, 8)
        Xb = F.one_hot(Xb, 27) # (1, 8, 27)
        Xb = Xb / 1.0 # (8, 27)
        Yb = Ytr[batch_num] # (8, 1)
        Yb = Yb.to(torch.long) # (8, 1)
        
### --------------------------------------------------------------------------------------------------------------        

        loss = 0
        
        if (max_iterations == 0):
            H[-1] = torch.zeros(1, hidden_size)
            C[-1] = torch.zeros(1, hidden_size)

        for t in range(time_steps):
            preact1[t] = Xb[t] @ Fvh + H[t-1] @ Fhh + bias1 # (1, 27) @ (27, 30) + (1, 30) @ (30, 30) + (30)
            preact2[t] = Xb[t]  @ i1vh + H[t-1]  @ i1hh * bias2 # (32, 27) @ (27, 30) + (32, 30) @ (30, 30) + (30)
            preact3[t] = Xb[t]  @ i2vh + H[t-1]  @ i2hh + bias3 # (32, 27) @ (27, 30) + (32, 30) @ (30, 30) + (30)
            preact4[t] = Xb[t]  @ Ovh + H[t-1]  @ Ohh + bias4 # (32, 27) @ (27, 30) + (32, 30) @ (30, 30) + (30)
            
            act1[t] = torch.sigmoid(preact1[t]) # (1, 30)
            act2[t] = torch.sigmoid(preact2[t]) # (1, 30)
            act3[t] = torch.tanh(preact3[t]) # (1, 30)
            act4[t] = torch.sigmoid(preact4[t]) # (1, 30)
            
            C[t] = act1[t] * C[t-1]  + act2[t]  * act3[t]  # (1, 30)
            Ct[t] = torch.tanh(C[t]) # (1, 30)
            H[t] = Ct[t] * act4[t]  # (1, 30)          

            logits[t] = H[t]  @ output_matrix + output_bias # (1, 30) @ (30, 27) + (1, 27) = (1, 27)

            # Cross entropy
            counts = logits[t].exp() # (1, 27)
            counts_sum = counts.sum(1, keepdims=True) # (1)
            counts_sum_inv = counts_sum**-1 # (1)
            probs = counts * counts_sum_inv # (1, 27)
            logprobs = probs.log() #(1, 27)
            loss += -logprobs[0, Yb[t]]
            
        if (max_iterations % 1000 == 0):
            print("counts_sum", counts_sum)

        # Continue the sequence for time step -1 of the next input sequence
        H[-1] = H[time_steps - 1]
        C[-1] = C[time_steps - 1]

        max_iterations += 1    
        
### ---------------------------------------------------------------------------------------------------------------
        # Backward pass
        # Set to zeros initially
        dHnext = torch.zeros_like(H[0]) # (1, 30)
        dCnext = torch.zeros_like(H[0]) # (1, 27)
        
        dFvh = torch.zeros(vocab_size, hidden_size)
        di1vh = torch.zeros(vocab_size, hidden_size)
        di2vh = torch.zeros(vocab_size, hidden_size)
        dOvh = torch.zeros(vocab_size, hidden_size)
        
        dFhh = torch.zeros(hidden_size, hidden_size)
        di1hh = torch.zeros(hidden_size, hidden_size)
        di2hh = torch.zeros(hidden_size, hidden_size)
        dOhh = torch.zeros(hidden_size, hidden_size)
        
        dbias1 = torch.zeros(1, hidden_size) # (30)
        dbias2 = torch.zeros(1, hidden_size) # (30)
        dbias3 = torch.zeros(1, hidden_size) # (30)
        dbias4 = torch.zeros(1, hidden_size) # (30)
        
        doutput_matrix = torch.zeros(hidden_size, vocab_size)  * 0.01 # (30, 27)
        doutput_bias = torch.zeros(1, vocab_size) # (30)

        for t in reversed(range(time_steps)):
            # Backpropogate cross entropy
            dlogits = F.softmax(logits[t], 1)
            dlogits [0, Yb] -= 1
            
            # Backpropogate output matrix and its bias
            doutput_matrix +=  (H[t].T) @ dlogits # (30, 1) @ (1, 27) = (30, 27)
            doutput_bias += dlogits # (1, 27)
            
            # Backpropogate into H
            dH = dlogits  @ output_matrix.T + dHnext # (1, 27) @ (27, 30) + (1, 30) = (1, 30)
            
            # Backpropogate dact4 (output gate activations)
            dact4  = dH  * Ct[t]  # (1, 30) * (1, 30) = (1, 30)
            
            # Backpropogate dC (current cell state)
            dC  = dH  * act4[t]  * (1 - torch.tanh(C[t]) **2) + dCnext # (1, 30) * (1, 30) * (1, 30) = (1, 30)
            
            ### Backpropogate act1 and previous cell state
            # Forget gate activations
            # dCnext activations
            dact1  = dC  * C[t-1] # (1, 30) * (1, 30) = (1, 30)
            dCnext = dC  * act1[t]
            
            # Backpropogate i1 activations
            dact2  = dC  * act3[t] # (1, 27)
            
            # Backpropogate i2 activations
            dact3  = dC  * act2[t]  # (1, 27)
            
            # Backpropogate all preactivations
            dpreact1  = dact1  * act1[t] * (1- act1[t])
            dpreact2  = dact2  * act2[t]  * (1- act2[t])
            dpreact3  = dact3  * (1 - torch.tanh(preact3[t])**2)
            dpreact4  = dact4  * act4[t]  * (1- act4[t])
            
            # Backpropogate gates
            dFvh += Xb[t].reshape(vocab_size, 1) @ dpreact1  # (27, 1) (1, 30) = (27, 30)
            dFhh += H[t-1].reshape(hidden_size, 1) @ dpreact1  # (30, 1) (1, 30) = (30, 30)
            dbias1 += dpreact1
            
            di1vh += Xb[t].reshape(vocab_size, 1) @ dpreact2 # (27, 1) (1, 30) = (27, 30)
            di1hh += H[t-1].reshape(hidden_size, 1) @ dpreact2 # (30, 1) (1, 30) = (30, 30)
            dbias2 += dpreact2
            
            di2vh += Xb[t].reshape(vocab_size, 1) @ dpreact3 # (27, 1) (1, 30) = (27, 30)
            di2hh += H[t-1].reshape(hidden_size, 1) @ dpreact3 # (30, 1) (1, 30) = (30, 30)
            dbias3 += dpreact3
            
            dOvh += Xb[t].reshape(vocab_size, 1) @ dpreact4 # (27, 1) (1, 30) = (27, 30)
            dOhh += H[t-1].reshape(hidden_size, 1) @ dpreact4 # (30, 1) (1, 30) = (30, 30)
            dbias4 += dpreact4
            
            # Backpropogate dHnext
            dHnext  = dpreact1  @ Fhh.T + dpreact2  @ i1hh.T + dpreact3  @ i2hh.T + dpreact4  @ Ohh.T
    
    ### ------------------------------------------------------------------------------------------------------------------
    
        # Update parameters using gradients
        Fvh -= lr * dFvh
        i1vh -= lr * di1vh
        i2vh -= lr * di2vh
        Ovh -= lr * dOvh

        Fhh -= lr * dFhh
        i1hh -= lr * di1hh
        i2hh -= lr * di2hh
        Ohh -= lr * dOhh
        
        bias1 -= lr * dbias1
        bias2 -= lr * dbias2
        bias3 -= lr * dbias3
        bias4 -= lr * dbias4

        output_matrix -= lr * doutput_matrix
        doutput_bias -= lr * doutput_bias



    

counts_sum tensor([[27.0007]])
counts_sum tensor([[27.0029]])
counts_sum tensor([[27.0163]])
counts_sum tensor([[27.0615]])
counts_sum tensor([[27.2335]])
counts_sum tensor([[27.8465]])
counts_sum tensor([[30.7204]])
counts_sum tensor([[64.6073]])
counts_sum tensor([[180105.9375]])
counts_sum tensor([[4.3857e+09]])


KeyboardInterrupt: 

In [17]:
output_matrix

tensor([[-324.0932, -324.1512,  -60.6865,  -82.8280, -124.9950, -324.0212,
          -20.4404,  -47.0357, -171.5341, -324.1687,  -68.0903, -117.7951,
         -283.1645, -148.7504, -323.6219, -180.4457,  -23.7667,   -7.0451,
         -276.2080, -179.7781, -121.6247,  -74.8806,  -60.3296,  -24.7178,
          -15.4333, -222.3771,  -57.2788],
        [ 324.7320,  324.6779,   60.7525,   82.9095,  125.1568,  324.5805,
           20.4604,   47.1652,  171.7828,  324.6581,   68.1179,  117.9171,
          283.5695,  149.0448,  324.0399,  180.7481,   23.7718,    7.0400,
          276.6554,  179.9780,  121.8557,   74.9900,   60.3949,   24.7211,
           15.4331,  222.5418,   57.2915],
        [-324.8392, -324.7778,  -60.7667,  -82.9027, -125.1790, -324.6648,
          -20.4745,  -47.1755, -171.8122, -324.7286,  -68.1422, -117.9584,
         -283.6296, -149.0522, -324.1298, -180.7840,  -23.7686,   -7.0099,
         -276.7013, -180.0337, -121.8341,  -74.9700,  -60.3927,  -24.7194,
          -15.

In [200]:
import torch

def sigmoid(x):
    return 1 / (1 + torch.exp(-x))

def sample_model(start_vector, Fvh, Fhh, i1vh, i1hh, i2vh, i2hh, Ovh, Ohh, bias1, bias2, bias3, bias4, output_matrix):
    """
    Generate a sequence of samples from the model.
    
    Parameters:
    - start_vector: Initial one-hot encoded vector to start the generation (torch tensor of shape (1, input_size))
    - Other parameters: Model weights and biases
    
    Returns:
    - Generated sequence (list of integers)
    """
    input_size = start_vector.shape[1]
    hidden_size = Fvh.shape[1]
    
    # Initialize hidden and cell states
    h = torch.zeros((1, hidden_size))
    c = torch.zeros((1, hidden_size))
    
    # Initialize the generated sequence with the index of the start vector
    generated_sequence = [torch.argmax(start_vector).item()]
    
    # Loop until '.' is generated or the maximum sequence length is reached
    while generated_sequence[-1] != 0 and len(generated_sequence) <= max_length:
        x = start_vector  # Use the provided start vector as input
        
        preact1 = x @ Fvh + h @ Fhh + bias1
        preact2 = x @ i1vh + h @ i1hh + bias2
        preact3 = x @ i2vh + h @ i2hh + bias3
        preact4 = x @ Ovh + h @ Ohh + bias4
        
        act1 = torch.sigmoid(preact1)
        act2 = torch.sigmoid(preact2)
        act3 = torch.tanh(preact3)
        act4 = torch.sigmoid(preact4)
        
        c = act1 * c + act2 * act3
        h = torch.tanh(c) * act4
        
        logits = h @ output_matrix
        probs = softmax(logits)
        
        # Sample from the probability distribution to get the next input
        next_index = torch.multinomial(probs.squeeze(), 1).item()
        
        generated_sequence.append(next_index)
        
        # Update the start vector with the one-hot encoded representation of the next index
        start_vector = torch.zeros((1, input_size))
        start_vector[0, next_index] = 1
        
    return [itos[ch] for ch in generated_sequence]

# Example usage
input_size = 27  # Size of the one-hot encoded vector
start_index = 1  # Index representing the starting point (e.g., 'a')
start_vector = torch.zeros((1, input_size))
start_vector[0, start_index] = 3  # One-hot encode the starting point

# Assume Fvh, Fhh, i1vh, i1hh, i2vh, i2hh, Ovh, Ohh, bias1, bias2, bias3, bias4, and output_matrix are already defined

max_length = 15  # Maximum length of the generated sequence


In [294]:
generated_sequence = sample_model(start_vector, Fvh, Fhh, i1vh, i1hh, i2vh, i2hh, Ovh, Ohh, bias1, bias2, bias3, bias4, output_matrix)
print(''.join(generated_sequence))

aquriizpiz.
